# Generated by Django 5.1.5 on 2025-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
